# Cluster Settings
cluster.name: distributed-logging-cluster
node.name: logging-node-1

# Path Settings
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

# Network
network.host: localhost
http.port: 9200

# Discovery
discovery.type: single-node

# Disable security for development
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false